server:
  port: 8081

database:
  host: localhost
  port: 5432
  user: scopeapi
  password: yourpassword
  dbname: scopeapi
  sslmode: disable

kafka:
  brokers:
    - localhost:9092
  topic: scopeapi-data
