environment: development

server:
  host: "0.0.0.0"
  port: "8080"

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "*"

static:
  path: "./dist"

logging:
  level: "debug"
  format: "json"

database:
  host: "localhost"
  port: 5432
  name: "scopeapi_admin"
  user: "scopeapi_user"
  password: "scopeapi_password"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

services:
  api_discovery:
    url: "http://localhost:8081"
  threat_detection:
    url: "http://localhost:8082"
  data_protection:
    url: "http://localhost:8083"
  gateway_integration:
    url: "http://localhost:8084"
  attack_blocking:
    url: "http://localhost:8085" 